// ReSharper disable UnusedMember.Global
// ReSharper disable PartialTypeWithSinglePart

namespace SwaggerToRestApi.Templates
{
    internal partial class ClientTemplate
    {
        internal const string FetchTemplate = @"
//----------------------
// <auto-generated>
//     Generated by SwaggerToRestApi library.
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

{% if stg.CustomComment and stg.CustomComment != empty and stg.CustomComment != blank -%}
/**
{% for cc in custom_comments -%}
 * {{ cc }}
{% endfor -%}
 */
{% endif -%}

export class {{ stg.ClientClassName }} {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
    }
}
";
    }
}